/**
 * Türkiye il -> ilçe listesi (isimler).
 * İlçe koordinatları burada saklanmaz; seçilen ilçe çalışma anında
 * OpenStreetMap (Nominatim) ile koordinata çevrilir, mesafe OSRM ile
 * gerçek karayolu rotasından hesaplanır. "" seçim = il merkezi.
 * Kaynak: enisbt/turkey-cities (isimler doğrulanmıştır).
 */
const DISTRICTS = {
  "Adana": ["aladağ","ceyhan","çukurova","feke","imamoğlu","karaisalı","karataş","kozan","pozantı","saimbeyli","sarıçam","seyhan","tufanbeyli","yumurtalık","yüreğir"],
  "Adıyaman": ["besni","çelikhan","gerger","gölbaşı","kahta","merkez","samsat","sincik","tut"],
  "Afyonkarahisar": ["başmakçı","bayat","bolvadin","çay","çobanlar","dazkırı","dinar","emirdağ","evciler","hocalar","ihsaniye","iscehisar","kızılören","merkez","sandıklı","sinanpaşa","sultandağı","şuhut"],
  "Ağrı": ["diyadin","doğubayazıt","eleşkirt","hamur","merkez","patnos","taşlıçay","tutak"],
  "Aksaray": ["ağaçören","eskil","gülağaç","güzelyurt","merkez","ortaköy","sarıyahşi","sultanhanı"],
  "Amasya": ["göynücek","gümüşhacıköy","hamamözü","merkez","merzifon","suluova","taşova"],
  "Ankara": ["akyurt","altındağ","ayaş","bala","beypazarı","çamlıdere","çankaya","çubuk","elmadağ","etimesgut","evren","gölbaşı","güdül","haymana","kahramankazan","kalecik","keçiören","kızılcahamam","mamak","nallıhan","polatlı","pursaklar","sincan","şereflikoçhisar","yenimahalle"],
  "Antalya": ["akseki","aksu","alanya","demre","döşemealtı","elmalı","finike","gazipaşa","gündoğmuş","ibradı","kaş","kemer","kepez","konyaaltı","korkuteli","kumluca","manavgat","muratpaşa","serik"],
  "Ardahan": ["çıldır","damal","göle","hanak","merkez","posof"],
  "Artvin": ["ardanuç","arhavi","borçka","hopa","kemalpaşa","merkez","murgul","şavşat","yusufeli"],
  "Aydın": ["bozdoğan","buharkent","çine","didim","efeler","germencik","incirliova","karacasu","karpuzlu","koçarlı","köşk","kuşadası","kuyucak","nazilli","söke","sultanhisar","yenipazar"],
  "Balıkesir": ["altıeylül","ayvalık","balya","bandırma","bigadiç","burhaniye","dursunbey","edremit","erdek","gömeç","gönen","havran","ivrindi","karesi","kepsut","manyas","marmara","savaştepe","sındırgı","susurluk"],
  "Bartın": ["amasra","kurucaşile","merkez","ulus"],
  "Batman": ["beşiri","gerçüş","hasankeyf","kozluk","merkez","sason"],
  "Bayburt": ["aydıntepe","demirözü","merkez"],
  "Bilecik": ["bozüyük","gölpazarı","inhisar","merkez","osmaneli","pazaryeri","söğüt","yenipazar"],
  "Bingöl": ["adaklı","genç","karlıova","kiğı","merkez","solhan","yayladere","yedisu"],
  "Bitlis": ["adilcevaz","ahlat","güroymak","hizan","merkez","mutki","tatvan"],
  "Bolu": ["dörtdivan","gerede","göynük","kıbrıscık","mengen","merkez","mudurnu","seben","yeniçağa"],
  "Burdur": ["ağlasun","altınyayla","bucak","çavdır","çeltikçi","gölhisar","karamanlı","kemer","merkez","tefenni","yeşilova"],
  "Bursa": ["büyükorhan","gemlik","gürsu","harmancık","inegöl","iznik","karacabey","keles","kestel","mudanya","mustafakemalpaşa","nilüfer","orhaneli","orhangazi","osmangazi","yenişehir","yıldırım"],
  "Çanakkale": ["ayvacık","bayramiç","biga","bozcaada","çan","eceabat","ezine","gelibolu","gökçeada","lapseki","merkez","yenice"],
  "Çankırı": ["atkaracalar","bayramören","çerkeş","eldivan","ılgaz","kızılırmak","korgun","kurşunlu","merkez","orta","şabanözü","yapraklı"],
  "Çorum": ["alaca","bayat","boğazkale","dodurga","iskilip","kargı","laçin","mecitözü","merkez","oğuzlar","ortaköy","osmancık","sungurlu","uğurludağ"],
  "Denizli": ["acıpayam","babadağ","baklan","bekilli","beyağaç","bozkurt","buldan","çal","çameli","çardak","çivril","güney","honaz","kale","merkezefendi","pamukkale","sarayköy","serinhisar","tavas"],
  "Diyarbakır": ["bağlar","bismil","çermik","çınar","çüngüş","dicle","eğil","ergani","hani","hazro","kayapınar","kocaköy","kulp","lice","silvan","sur","yenişehir"],
  "Düzce": ["akçakoca","cumayeri","çilimli","gölyaka","gümüşova","kaynaşlı","merkez","yığılca"],
  "Edirne": ["enez","havsa","ipsala","keşan","lalapaşa","meriç","merkez","süloğlu","uzunköprü"],
  "Elazığ": ["ağın","alacakaya","arıcak","baskil","karakoçan","keban","kovancılar","maden","merkez","palu","sivrice"],
  "Erzincan": ["çayırlı","iliç","kemah","kemaliye","merkez","otlukbeli","tercan","üzümlü"],
  "Erzurum": ["aşkale","aziziye","çat","hınıs","horasan","ispir","karaçoban","karayazı","köprüköy","narman","oltu","olur","palandöken","pasinler","pazaryolu","şenkaya","tekman","tortum","uzundere","yakutiye"],
  "Eskişehir": ["alpu","beylikova","çifteler","günyüzü","han","inönü","mahmudiye","mihalgazi","mihalıççık","odunpazarı","sarıcakaya","seyitgazi","sivrihisar","tepebaşı"],
  "Gaziantep": ["araban","islahiye","karkamış","nizip","nurdağı","oğuzeli","şahinbey","şehitkamil","yavuzeli"],
  "Giresun": ["alucra","bulancak","çamoluk","çanakçı","dereli","doğankent","espiye","eynesil","görele","güce","keşap","merkez","piraziz","şebinkarahisar","tirebolu","yağlıdere"],
  "Gümüşhane": ["kelkit","köse","kürtün","merkez","şiran","torul"],
  "Hakkari": ["çukurca","derecik","merkez","şemdinli","yüksekova"],
  "Hatay": ["altınözü","antakya","arsuz","belen","defne","dörtyol","erzin","hassa","iskenderun","kırıkhan","kumlu","payas","reyhanlı","samandağ","yayladağı"],
  "Iğdır": ["aralık","karakoyunlu","merkez","tuzluca"],
  "Isparta": ["aksu","atabey","eğirdir","gelendost","gönen","keçiborlu","merkez","senirkent","sütçüler","şarkikaraağaç","uluborlu","yalvaç","yenişarbademli"],
  "İstanbul": ["adalar","arnavutköy","ataşehir","avcılar","bağcılar","bahçelievler","bakırköy","başakşehir","bayrampaşa","beşiktaş","beykoz","beylikdüzü","beyoğlu","büyükçekmece","çatalca","çekmeköy","esenler","esenyurt","eyüpsultan","fatih","gaziosmanpaşa","güngören","kadıköy","kağıthane","kartal","küçükçekmece","maltepe","pendik","sancaktepe","sarıyer","silivri","sultanbeyli","sultangazi","şile","şişli","tuzla","ümraniye","üsküdar","zeytinburnu"],
  "İzmir": ["aliağa","balçova","bayındır","bayraklı","bergama","beydağ","bornova","buca","çeşme","çiğli","dikili","foça","gaziemir","güzelbahçe","karabağlar","karaburun","karşıyaka","kemalpaşa","kınık","kiraz","konak","menderes","menemen","narlıdere","ödemiş","seferihisar","selçuk","tire","torbalı","urla"],
  "Kahramanmaraş": ["afşin","andırın","çağlayancerit","dulkadiroğlu","ekinözü","elbistan","göksun","nurhak","onikişubat","pazarcık","türkoğlu"],
  "Karabük": ["eflani","eskipazar","merkez","ovacık","safranbolu","yenice"],
  "Karaman": ["ayrancı","başyayla","ermenek","kazımkarabekir","merkez","sarıevliler"],
  "Kars": ["akyaka","arpaçay","digor","kağızman","merkez","sarıkamış","selim","susuz"],
  "Kastamonu": ["abana","ağlı","araç","azdavay","bozkurt","cide","çatalzeytin","daday","devrekani","doğanyurt","hanönü","ihsangazi","inebolu","küre","merkez","pınarbaşı","seydiler","şenpazar","taşköprü","tosya"],
  "Kayseri": ["akkışla","bünyan","develi","felahiye","hacılar","incesu","kocasinan","melikgazi","özvatan","pınarbaşı","sarıoğlan","sarız","talas","tomarza","yahyalı","yeşilhisar"],
  "Kırıkkale": ["bahşili","balışeyh","çelebi","delice","karakeçili","keskin","merkez","sulakyurt","yahşihan"],
  "Kırklareli": ["babaeski","demirköy","kofçaz","lüleburgaz","merkez","pehlivanköy","pınarhisar","vize"],
  "Kırşehir": ["akçakent","akpınar","boztepe","çiçekdağı","kaman","merkez","mucur"],
  "Kilis": ["elbeyli","merkez","musabeyli","polateli"],
  "Kocaeli": ["başiskele","çayırova","darıca","derince","dilovası","gebze","gölcük","izmit","kandıra","karamürsel","kartepe","körfez"],
  "Konya": ["ahırlı","akören","akşehir","altınekin","beyşehir","bozkır","cihanbeyli","çeltik","çumra","derbent","derebucak","doğanhisar","emirgazi","ereğli","güneysınır","hadim","halkapınar","hüyük","ılgın","kadınhanı","karapınar","karatay","kulu","meram","sarayönü","selçuklu","seydişehir","taşkent","tuzlukçu","yalıhüyük","yunak"],
  "Kütahya": ["altıntaş","aslanapa","çavdarhisar","domaniç","dumlupınar","emet","gediz","hisarcık","merkez","pazarlar","simav","şaphane","tavşanlı"],
  "Malatya": ["akçadağ","arapgir","arguvan","battalgazi","darende","doğanşehir","doğanyol","hekimhan","kale","kuluncak","pütürge","yazıhan","yeşilyurt"],
  "Manisa": ["ahmetli","akhisar","alaşehir","demirci","gölmarmara","gördes","kırkağaç","köprübaşı","kula","salihli","sarıgöl","saruhanlı","selendi","soma","şehzadeler","turgutlu","yunusemre"],
  "Mardin": ["artuklu","dargeçit","derik","kızıltepe","mazıdağı","midyat","nusaybin","ömerli","savur","yeşilli"],
  "Mersin": ["akdeniz","anamur","aydıncık","bozyazı","çamlıyayla","erdemli","gülnar","mezitli","mut","silifke","tarsus","toroslar","yenişehir"],
  "Muğla": ["bodrum","dalaman","datça","fethiye","kavaklıdere","köyceğiz","marmaris","menteşe","milas","ortaca","seydikemer","ula","yatağan"],
  "Muş": ["bulanık","hasköy","korkut","malazgirt","merkez","varto"],
  "Nevşehir": ["acıgöl","avanos","derinkuyu","gülşehir","hacıbektaş","kozaklı","merkez","ürgüp"],
  "Niğde": ["altunhisar","bor","çamardı","çiftlik","merkez","ulukışla"],
  "Ordu": ["akkuş","altınordu","aybastı","çamaş","çatalpınar","çaybaşı","fatsa","gölköy","gülyalı","gürgentepe","ikizce","kabadüz","kabataş","korgan","kumru","mesudiye","perşembe","ulubey","ünye"],
  "Osmaniye": ["bahçe","düziçi","hasanbeyli","kadirli","merkez","sumbas","toprakkale"],
  "Rize": ["ardeşen","çamlıhemşin","çayeli","derepazarı","fındıklı","güneysu","hemşin","ikizdere","iyidere","kalkandere","merkez","pazar"],
  "Sakarya": ["adapazarı","akyazı","arifiye","erenler","ferizli","geyve","hendek","karapürçek","karasu","kaynarca","kocaali","pamukova","sapanca","serdivan","söğütlü","taraklı"],
  "Samsun": ["19 mayıs","alaçam","asarcık","atakum","ayvacık","bafra","canik","çarşamba","havza","ilkadım","kavak","ladik","salıpazarı","tekkeköy","terme","vezirköprü","yakakent"],
  "Siirt": ["baykan","eruh","kurtalan","merkez","pervari","şirvan","tillo"],
  "Sinop": ["ayancık","boyabat","dikmen","durağan","erfelek","gerze","merkez","saraydüzü","türkeli"],
  "Sivas": ["akıncılar","altınyayla","divriği","doğanşar","gemerek","gülova","gürün","hafik","imranlı","kangal","koyulhisar","merkez","suşehri","şarkışla","ulaş","yıldızeli","zara"],
  "Şanlıurfa": ["akçakale","birecik","bozova","ceylanpınar","eyyübiye","halfeti","haliliye","harran","hilvan","karaköprü","siverek","suruç","viranşehir"],
  "Şırnak": ["beytüşşebap","cizre","güçlükonak","idil","merkez","silopi","uludere"],
  "Tekirdağ": ["çerkezköy","çorlu","ergene","hayrabolu","kapaklı","malkara","marmaraereğlisi","muratlı","saray","süleymanpaşa","şarköy"],
  "Tokat": ["almus","artova","başçiftlik","erbaa","merkez","niksar","pazar","reşadiye","sulusaray","turhal","yeşilyurt","zile"],
  "Trabzon": ["akçaabat","araklı","arsin","beşikdüzü","çarşıbaşı","çaykara","dernekpazarı","düzköy","hayrat","köprübaşı","maçka","of","ortahisar","sürmene","şalpazarı","tonya","vakfıkebir","yomra"],
  "Tunceli": ["çemişgezek","hozat","mazgirt","merkez","nazımiye","ovacık","pertek","pülümür"],
  "Uşak": ["banaz","eşme","karahallı","merkez","sivaslı","ulubey"],
  "Van": ["bahçesaray","başkale","çaldıran","çatak","edremit","erciş","gevaş","gürpınar","ipekyolu","muradiye","özalp","saray","tuşba"],
  "Yalova": ["altınova","armutlu","çınarcık","çiftlikköy","merkez","termal"],
  "Yozgat": ["akdağmadeni","aydıncık","boğazlıyan","çandır","çayıralan","çekerek","kadışehri","merkez","saraykent","sarıkaya","sorgun","şefaatli","yenifakıllı","yerköy"],
  "Zonguldak": ["alaplı","çaycuma","devrek","ereğli","gökçebey","kilimli","kozlu","merkez"],
};
